### ISSUE TITLE
FILE [dll] is not valid in 2023 but it is in 2024

### ISSUE THREAD

**Issue by davilavanegas** [chuongmep/CadAddinManager#10]
dll info:
accoremdg C:\Program Files\Autodesk\AutoCAD 2023\accoremgd.dll version 24.2.0.0 

when i try to open on 2023 a msgbox display file is not valid so I try on C3D 2024 and load fine. Get back to C3D 2023 and now dll is load
![image](https://github.com/chuongmep/CadAddinManager/assets/135153445/a37c8b97-6c4d-4207-b28b-d3136a9e79bf)

but when I run a single command to get RXClass follow message is shown on command line 

```
Command: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'accoremgd, Version=24.2.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.TypeReference.Resolve()
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
   at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute attribute, Collection`1 parameters)
   at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute attribute)
   at Mono.Cecil.CustomAttribute.<Resolve>b__35_0(CustomAttribute attribute, MetadataReader reader)
   at Mono.Cecil.ModuleDefinition.Read[TItem](TItem item, Action`2 read)
   at Mono.Cecil.CustomAttribute.Resolve()
   at Mono.Cecil.CustomAttribute.get_ConstructorArguments()
   at CadAddinManager.Model.AssemLoader.ResolveDuplicateMethod(String originalFilePath)
   at CadAddinManager.Model.AssemLoader.LoadAddinsToTempFolder(String originalFilePath, Boolean parsingOnly)
   at CadAddinManager.Command.AddinManagerBase.RunActiveCommand()
```
Same command on 2024

![image](https://github.com/chuongmep/CadAddinManager/assets/135153445/d97c92e7-54fb-42db-bb7b-0161e581143d)

**Comment by chuongmep** [comment]
Hi @davilavanegas 

Apologies for the delay; I've been on vacation. I'd like to address the issue you're encountering regarding loading different assemblies. Allow me to provide you with a detailed explanation of the problem and how to resolve it effectively.

When working with CadAddinManager, it's crucial to adhere to certain rules:

 - Ensure that you're loading the correct assembly for the Cad version you're using. For instance, if you're developing for Cad version 2023, make sure to reference assemblies corresponding to the 2023 version.

- Be vigilant about browsing if you're developing for multiple versions. It's essential to remember that the path will always load from the same location as the last time. Therefore, consistently check and update the paths to prevent any issues.

By following these guidelines, you can streamline your development process and mitigate any potential complications associated with loading different assemblies.

Let me know if you need further clarification or assistance with anything else.
